// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaESM7Axb9uo1j19KsBBVmM-lK7rypMzY',
    appId: '1:720882125679:web:c58e3b3e73ccb07728b69a',
    messagingSenderId: '720882125679',
    projectId: 'feedback-appss',
    authDomain: 'feedback-appss.firebaseapp.com',
    storageBucket: 'feedback-appss.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEFgW_Y-AgM2h2SaduW86xeCRC2C0slrs',
    appId: '1:720882125679:android:e1d86b07aaf8b54428b69a',
    messagingSenderId: '720882125679',
    projectId: 'feedback-appss',
    storageBucket: 'feedback-appss.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBiMnY4tNiFlHtH7D6YJn9VXC31MCeC9Q',
    appId: '1:720882125679:ios:e8e97f7bc925da4128b69a',
    messagingSenderId: '720882125679',
    projectId: 'feedback-appss',
    storageBucket: 'feedback-appss.firebasestorage.app',
    iosBundleId: 'e',
  );
}
